FROM node:12.22.3 as build 
RUN npm install -g @angular/cli@8.3.12
COPY app /app
WORKDIR app
RUN npm run lint
RUN npm install && ng build --prod --aot --no-progress

FROM trion/ng-cli-karma:12.1.1 as test
COPY --from=build /app/* .
RUN ng test --watch=false --progress=false

FROM alpine:3.10
WORKDIR static
COPY --from=ANGULAR_BUILD /app/dist/app/* .
